### PR TITLE
Add new fan-created clothing pages

### PR DESCRIPTION
**Pull request by Dhelayan**
These pages have been added on the official MOULa server lately and should be included in the .age file here aswell.

### CODE REVIEW

**Comment by Deledrius** [comment]
That seems like a good idea, but it looks like nothing's been committed upstream yet: https://bitbucket.org/OpenUru_org/moulscript-ou/commits/all
Are these on the live server currently?

**Comment by Hoikas** [comment]
Yes, but should they be a requirement in our repo? I haven't actually looked at these items.

**Comment by Dhelayan** [comment]
Forget the OpenURU.org stuff, they don't update anything ever. Also, yes these pages are live on the MOULa server currently. They contain a few new shirts, that's it, but i don't see a reason why they shouldn't be included in the age file. Shouldn't the age files be on par with the official/live ones?

**Comment by Deledrius** [comment]
In theory, but since the initial drop there hasn't been a single update from Cyan to the .sdl or the .age files, so we've not yet had to deal with that question explicitly.

**Comment by cwalther** [comment]
Upstream isn’t https://bitbucket.org/OpenUru_org/moulscript-ou but https://bitbucket.org/OpenUru_org/moulscript, but yeah, nothing has turned up there yet either. I’ll ping Mark about it.

**Comment by Deledrius** [comment]
Thanks @cwalther , I checked them both and couldn't remember which was which (and neither had recent activity).

**Comment by cwalther** [comment]
CWE+MOULSCRIPT are the Cyan-maintained repos that should match what’s on MOULa. {CWE|MOULSCRIPT}-ou are the OU-maintained forks that Cyan occasionally takes fan contributions from (and unfortunately haven’t had any updates for a long time because we haven’t been able to test the pending stuff on Minkata yet – but we’re working on it).

**Comment by Dhelayan** [comment]
However neither of those do have the new pages added in the age file, to go back to topic. Would be nice if that could be done, since otherwise MOULa server and repo wouldn't match..

**Comment by cwalther** [comment]
Here we go: http://foundry.openuru.org/hg/MOULSCRIPT/rev/72440f142039. Note that the file there, which I have verified to match the one from MOULa, is not the same as Dhelayan’s – the lines are in a different order.

Also of note, Mark says:
> In the course of testing with Chloe's clothing prp files, I made the discovery that the Avatar system finds all the pages in the GlobalClothing age, regardless if it is mentioned in the .age file or not. I didn't look to see how that works, it just does.

I have not checked that, but it would mean that this change is actually not strictly necessary.

**Comment by Dhelayan** [comment]
Interesting! Lovely to see how Cyan has no idea what they're doing with Plasma. Regardless, i'd say we can close this then :+1:

**Pull request merged**
